trigger:
- '*'

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
# Use the .NET 6 SDK
- task: UseDotNet@2
  displayName: 'Use .NET SDK 6.x'
  inputs:
    packageType: 'sdk'
    version: '6.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

# Restore Node packages
- task: Npm@1
  displayName: 'Install Node.js packages'
  inputs:
    command: 'install'
    workingDir: 'Tailspin.SpaceGame.Web'

# Compile Sass using node-sass
- script: |
    ./node_modules/.bin/node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot
  displayName: 'Compile Sass assets'

# Run Gulp tasks
- task: Gulp@1
  displayName: 'Run Gulp tasks'
  inputs:
    gulpFile: 'Tailspin.SpaceGame.Web/gulpfile.js'
    targets: 'default'
    workingDirectory: 'Tailspin.SpaceGame.Web'

# Write build info
- script: |
    echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt
  displayName: 'Write build info'
  workingDirectory: 'Tailspin.SpaceGame.Web/wwwroot'

# Restore .NET dependencies
- task: DotNetCoreCLI@2
  displayName: 'Restore .NET project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

# Build the project
- task: DotNetCoreCLI@2
  displayName: 'Build the .NET project'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration $(buildConfiguration)'
    projects: '**/*.csproj'
