trigger:
- '*'

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
# Install .NET 8 SDK
- task: UseDotNet@2
  displayName: 'Use .NET SDK 8.x'
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet


# Install Node.js packages (gulp, sass, etc.)
- task: Npm@1
  displayName: 'Install Node.js packages'
  inputs:
    command: 'install'
    workingDir: 'Tailspin.SpaceGame.Web'

# Run Gulp tasks (compiles Sass and minifies assets)
- task: Gulp@1
  displayName: 'Run Gulp tasks'
  inputs:
    gulpFile: 'gulpfile.js'
    targets: 'default'
    workingDirectory: '.'

# Write build info to wwwroot
- script: |
    echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt
  displayName: 'Write build info'
  workingDirectory: 'Tailspin.SpaceGame.Web/wwwroot'

# Restore .NET dependencies
- task: DotNetCoreCLI@2
  displayName: 'Restore .NET project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

# Build the .NET project
- task: DotNetCoreCLI@2
  displayName: 'Build the .NET project'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration $(buildConfiguration)'
    projects: '**/*.csproj'
